FROM docker.elastic.co/elasticsearch/elasticsearch:6.4.0
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-stempel


